### ISSUE TITLE
ConfiguredDatabaseClientFactory should use Bean class

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/ml-javaclient-util#105]
The DatabaseClientFactory.Bean class should be able to handle everything once it's fully working (apparently getting patched soon in a new Java Client release).

**Comment by rjrudin** [comment]
Pushing this to 3.13.0. This isn't removing as much code as I had hoped, as the Bean class doesn't yet construct a SecurityContextType.

**Comment by rjrudin** [comment]
Never mind, forgot there was a PR for it.

**Comment by rjrudin** [comment]
Reopening this - ran into errors when it's not digest or basic auth:

```
java.lang.IllegalStateException: makeSecurityContext should only be called with BASIC or DIGEST Authentication

	at com.marklogic.client.DatabaseClientFactory.makeSecurityContext(DatabaseClientFactory.java:843)
	at com.marklogic.client.DatabaseClientFactory.access$200(DatabaseClientFactory.java:52)
	at com.marklogic.client.DatabaseClientFactory$Bean.newClient(DatabaseClientFactory.java:1287)
	at com.marklogic.client.ext.DefaultConfiguredDatabaseClientFactory.newDatabaseClient(DefaultConfiguredDatabaseClientFactory.java:38)
```

**Comment by rjrudin** [comment]
Closing, not worth pursuing
